package dev.modularui.preview.project;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class PreviewProjectTest {

    @TempDir
    Path temporaryDirectory;

    @Test
    void discoversThePortableProjectInputsInDeterministicOrder() throws Exception {
        Path projectRoot = temporaryDirectory.resolve("machine-preview");
        Path sources = Files.createDirectories(projectRoot.resolve("src/preview/java"));
        Path resources = Files.createDirectories(projectRoot.resolve("src/preview/resources"));
        Path assets = Files.createDirectories(projectRoot.resolve("assets"));
        Path libraries = Files.createDirectories(projectRoot.resolve("libs"));
        Path extensions = Files.createDirectories(projectRoot.resolve("extensions"));
        Path firstLibrary = Files.write(libraries.resolve("a-library.jar"), new byte[0]);
        Path secondLibrary = Files.write(libraries.resolve("b-library.jar"), new byte[0]);
        Path extension = Files.write(extensions.resolve("machine-extension.jar"), new byte[0]);
        Files.writeString(projectRoot.resolve("preview.properties"), "screen.width=1600\nscenario=running\n");

        PreviewProject project = PreviewProject.open(projectRoot);

        assertEquals(projectRoot.toAbsolutePath().normalize(), project.root());
        assertEquals(sources, project.previewSources());
        assertEquals(List.of(resources, assets), project.assetSources());
        assertEquals(List.of(firstLibrary, secondLibrary), project.libraries());
        assertEquals(List.of(extension), project.extensions());
        assertEquals("1600", project.property("screen.width").orElseThrow());
        assertEquals("running", project.property("scenario").orElseThrow());
    }

    @Test
    void loadsProductionRuntimeEntriesFromTheProjectClasspathFile() throws Exception {
        Path projectRoot = Files.createDirectories(temporaryDirectory.resolve("production-preview"));
        Path productionClasses = Files.createDirectories(projectRoot.resolve("build/production-classes"));
        Path externalLibrary = Files.write(temporaryDirectory.resolve("production-library.jar"), new byte[0]);
        Files.writeString(
            projectRoot.resolve("runtime-classpath.txt"),
            "# Generated by the production build\n"
                + "build/production-classes\n"
                + externalLibrary
                + "\n");

        PreviewProject project = PreviewProject.open(projectRoot);

        assertEquals(List.of(productionClasses, externalLibrary), project.productionRuntime());
        assertTrue(project.runtimeArtifacts().containsAll(List.of(productionClasses, externalLibrary)));
    }

    @Test
    void suppliesTheBundledModularUiRuntimeToEveryProject() throws Exception {
        Path projectRoot = Files.createDirectories(temporaryDirectory.resolve("standalone-preview"));
        Path modularUiArtifact = Path.of(System.getProperty("modularui.test.jar"))
            .toRealPath();

        PreviewProject project = PreviewProject.open(projectRoot);

        assertTrue(project.runtimeArtifacts()
            .stream()
            .map(path -> {
                try {
                    return path.toRealPath();
                } catch (java.io.IOException exception) {
                    throw new java.io.UncheckedIOException(exception);
                }
            })
            .anyMatch(modularUiArtifact::equals));
    }
}
